os: linux

language: android

licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28 # match your targetVersion

jdk: oraclejdk8

sudo: false

addons:
  apt:
    # Flutter depends on /usr/lib/x86_64-linux-gnu/libstdc++.so.6 version GLIBCXX_3.4.18
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid

cache:
  directories:
    - "$HOME/.pub-cache"

install:
  - git clone https://github.com/flutter/flutter.git -b stable --depth 1
  - export PATH=./flutter/bin:$PATH
  - flutter doctor

script:
  - flutter packages get
  - flutter build apk
#  - flutter analyze --no-pub --no-current-package lib/ test/
#  - flutter test --no-pub test/

env:
  - APK_NAME="smart_home_app_${TRAVIS_TAG}.apk"

before_deploy:
  - mv build/app/outputs/apk/release/app-release.apk $APK_NAME

deploy:
  provider: releases
  api_key: $GITHUB_OAUTH_TOKEN
  file: $APK_NAME
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
    branch: master
    repo: e154/smart-home-app
  branches:
    only:
      - master
      - /^v\d+(\.\d+)+$/

